blacklist:
  - config_split.config_split.fcs
  - system.site
  - system.theme
  - core.extension
  - asset_injector.css.fcs_inyeccion_css
  - core.entity_view_mode.shortcut.token
  - shortcut.set.default
  - unizar_centro.settings
  - unizar_base.settings
  - unizar_departamento.settings
  - smtp.settings
  - language.negociation
  - language.types
  - unizar_modulos_configuracion.settings
  - unizar_admin_menu.settings
  - migrate_drupal.settings
  - webform.webform.*
  - system.menu.*
  - language.entity.*
  - block.block.*
dependencies: {}
description: ''
folder: ../config/sites/fcs
graylist: {}
graylist_dependents: true
graylist_skip_equal: true
id: fcs
label: fcs
langcode: es
module:
  c11n_migrate: 0
status: true
theme: {}
weight: 0
