_core:
  default_config_hash: DxlVgRgV9lXMAkbI6xQqpf_Qbe4useWC1itoqrvimWs
favicon_path: ''
favicon_upload: ''
id_centro: '226'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=226&colectivo=TODOS'
nombre_centro: 'Departamento de Historia'
dir_centro: 'Direcci√≥n del centro'
telefono_centro: '976 76 21 39 - 976 67 21 38'
mail_centro: sed3012@unizar.es
url_mapa: 'https://www.google.es/maps/place/Facultad+de+Filosof%C3%ADa+y+Letras/@41.6436942,-0.9005182,19z/data=!4m5!3m4!1s0xd5914d7112a4f4'
logo_blanco: '274'
facebook: ''
twitter: ''
instagram: ''
meta_desc: ''
langcode: es
rrs_header: 0
blog: ''
youtube: ''
linkedin: ''
soundcloud: ''
id: ''
dir_centro2: ''
mail_centro2: ''
telefono_centro2: ''
url_mapa2: ''
