_core:
  default_config_hash: 0dQ8EaP-3Gas02Htm0SWvarYJkL93Xa4MTe53x-PwuE
favicon_path: ''
favicon_upload: ''
id_centro: '79'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=79&colectivo=TODOS'
nombre_centro: 'Departamento de Análisis Económico'
dir_centro: 'Gran Vía, 2 | 50005 Zaragoza'
telefono_centro: '976 761 831'
mail_centro: sed4000@unizar.es
url_mapa: 'https://www.google.es/maps/place/41%C2%B038"44.4%22N+0%C2%B053"45.2%22W/@41.645653,-0.895882,930m/data=!3m2!1e3!4b1!4m2!3m1!1s0x'
logo_blanco: '9'
facebook: ''
twitter: ''
meta_desc: 'El Departamento de Análisis Económico de la Universidad de Zaragoza ejerce competencias de docencia e investigación en el área de Fundamentos del Análisis Económico a través de las disciplinas de Macroeconomía, Microeconomía, Matemáticas y Econometría.'
langcode: es
