_core:
  default_config_hash: 2B_QojuKbw52utt_2PdocaA_XceWXKmFt0hspR9FTrU
favicon_path: ''
favicon_upload: ''
id_centro: '224'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=224&colectivo=TODOS'
nombre_centro: 'Departamento de Didácticas Específicas'
dir_centro: 'Facultad de Educación | Pedro Cerbuna, 12 | 50009 Zaragoza'
telefono_centro: '976 76 13 02'
mail_centro: sed4013@unizar.es
url_mapa: 'https://www.google.es/maps/place/41%C2%B038"44.4%22N+0%C2%B053"45.2%22W/@41.645653,-0.895882,930m/data=!3m2!1e3!4b1!4m2!3m1!1s0x'
logo_blanco: '70'
facebook: ''
twitter: ''
instagram: ''
meta_desc: ''
langcode: es
