_core:
  default_config_hash: x4vQ9QDUOkBP1xFZpTiMHQZB6bQUS7X4D-l2c5XxGOU
favicon_path: ''
favicon_upload: ''
id: '38'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=38&colectivo=TODOS'
nombre_centro: 'Departamento de Física Teórica'
dir_centro: 'Facultad de Ciencias | Pedro Cerbuna, 12 | 50009 Zaragoza'
telefono_centro: '976 761 262'
mail_centro: sed2004@unizar.es
url_mapa: 'https://www.google.es/maps/place/41%C2%B038"30.1%22N+0%C2%B053"59.6%22W/@41.64152,-0.8996867,930m/data=!3m2!1e3!4b1!4m2!3m1!1s0x'
logo_blanco: '8'
facebook: ''
twitter: ''
meta_desc: 'Página web del Departamento de Física Teórica de la Universidad de Zaragoza'
langcode: es
rrs_header: 0
blog: ''
instagram: ''
youtube: ''
linkedin: ''
soundcloud: ''
id_centro: '38'
dir_centro2: ''
mail_centro2: ''
telefono_centro2: ''
url_mapa2: ''
