_core:
  default_config_hash: WEQgYKJY57uwvOMUtfGDQJEE1T885wd3opya-C9qtV0
favicon_path: 'public://icirce.ico'
favicon_upload: ''
id: C109
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=C109&colectivo=TODOS'
nombre_centro: 'Instituto Universitario de Investigación Mixto CIRCE'
dir_centro: 'Edificio CIRCE - Mariano Esquillor Gómez, 15'
telefono_centro: '976762145 - 976762978'
mail_centro: icirce@unizar.es
url_mapa: 'https://goo.gl/maps/DsLN32ygLRaiA4Gh7'
logo_blanco: '357'
facebook: 'https://www.facebook.com/pages/category/Education-Website/Instituto-CIRCE-2341788526065946/'
twitter: 'https://twitter.com/InstitutoCIRCE'
instagram: ''
youtube: ''
meta_desc: 'Instituto Universitario Investigación CIRCE Universidad Zaragoza Máster Europeo Energías Renovables Eficiencia Energética Sostenibilidad Formación icirce'
favicon_mimetype: image/vnd.microsoft.icon
langcode: es
