_core:
  default_config_hash: bpK9zJFL2Iw0wFJ1x9wmOrt-eGFG3_TS3TXj_xc9UVk
favicon_path: ''
favicon_upload: ''
id_centro: '81'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=81&colectivo=TODOS'
nombre_centro: 'Derecho Privado'
dir_centro: 'Pedro Cerbuna, 12 - 50009 ZARAGOZA'
telefono_centro: '976 76 14 68'
mail_centro: sed4004@unizar.es
url_mapa: 'https://www.google.es/maps/place/41%C2%B038"44.4%22N+0%C2%B053"45.2%22W/@41.645653,-0.895882,930m/data=!3m2!1e3!4b1!4m2!3m1!1s0x'
logo_blanco: '19'
facebook: ''
twitter: ''
instagram: ''
meta_desc: ''
langcode: es
