_core:
  default_config_hash: 4rJQEXPhLNIz513MVclfHFNhhGuimY1iW1VUhRAJbrg
favicon_path: ''
favicon_upload: ''
id_centro: '58'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=58&colectivo=TODOS'
nombre_centro: 'Departamento de Ingeniería Electronica y Comunicaciones'
dir_centro: 'C/ María de Luna 1 -  50018 Zaragoza'
telefono_centro: '+34 976 761948'
mail_centro: sed5008@unizar.es
url_mapa: 'https://www.google.es/maps/place/Edificio+Ada+Byron,+Mar%C3%ADa+de+Luna,+3,+50018+Zaragoza/@41.6839494,-0.8910451,17z/data=!3m1!'
logo_blanco: '7'
facebook: ''
twitter: ''
meta_desc: 'DEPARTAMENTO ELECTRONICA COMUNICACIONES DIEC UNIVERSIDAD'
langcode: es
