_core:
  default_config_hash: US-lBLCBn_H3fGXTJfOEvqIL9BgA0aTH0S1pL1pesdI
favicon_path: ''
favicon_upload: ''
id_centro: '118'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=118&colectivo=TODOS'
nombre_centro: 'Departamento de Contabilidad y Finanzas'
dir_centro: 'Facultad de Economía y Empresa, Gran Vía 2, Zaragoza'
telefono_centro: '976 76 1791'
mail_centro: sed4002@unizar.es
url_mapa: 'https://www.google.es/maps/place/Facultad+De+Econom%C3%ADa+Y+Empresa/@41.6465326,-0.8899406,17z/data=!3m1!4b1!4m2!3m1!1s0xd5914d'
logo_blanco: '8'
facebook: ''
twitter: ''
meta_desc: ''
langcode: es
