blacklist:
- config_split.config_split.medicina
- system.site
- system.theme
- asset_injector.css.medicina_inyeccion_css
- core.entity_view_mode.shortcut.token
- shortcut.set.default
- unizar_centro.settings
- unizar_base.settings
- unizar_departamento.settings
- smtp.settings
- language.types
- matomo.settings
- unizar_modulos_configuracion.settings
- unizar_admin_menu.settings
- migrate_drupal.settings
- webform.webform.*
- system.menu.*
- language.entity.*
- block.block.*
- language.negotiation
- user.role.administrator
- user.role.anonymous
dependencies: {}
description: ''
folder: ../config/sites/centros/comun/medicina
graylist: {}
graylist_dependents: true
graylist_skip_equal: true
id: medicina
label: medicina
langcode: es
module:
  c11n_migrate: 0
status: true
theme:
  unizar_centro: 0
uuid: 660f4097-4ec8-41d5-ad55-bfb06cbdcf3e
weight: 0
