_core:
  default_config_hash: b3Q8yQ0WlaKrG7MbjyYw4cT0hrhe3SqMM1RxCSAKJDw
logo_path: 'public://logo-eupt-pace_0.png'
favicon_path: ''
favicon_upload: ''
id_centro: '326'
nombre_centro: 'Escuela Universitaria Politécnica de Teruel'
dir_centro: 'C/Atarazana, nº2, 44003 Teruel'
telefono_centro: '+34 978 618 102'
mail_centro: diringtt@unizar.es
url_mapa: /contacto
dir_centro2: ''
telefono_centro2: ''
mail_centro2: ''
url_mapa2: ''
logo_blanco: '2589'
imagen_segundas: '1622'
facebook: ''
twitter: ''
youtube: ''
linkedin: ''
instagram: ''
blog: ''
blog_class: ''
soundcloud: ''
meta_desc: ''
langcode: es
