blacklist: [config_split.config_split.bioquimica, system.site, system.theme, core.extension,
  asset_injector.css.bioquimica_inyeccion_css, core.entity_view_mode.shortcut.token,
  shortcut.set.default, unizar_centro.settings, unizar_base.settings, unizar_departamento.settings,
  smtp.settings, language.negociation, language.types, unizar_modulos_configuracion.settings,
  unizar_admin_menu.settings, migrate_drupal.settings, webform.webform.*, system.menu.*,
  language.entity.*, block.block.*, config_split.config_split.departamento.yml]
dependencies: {}
description: ''
folder: ../config/sites/bioquimica
graylist: {}
graylist_dependents: true
graylist_skip_equal: true
id: bioquimica
label: bioquimica
langcode: es
module: {c11n_migrate: 0}
status: true
theme: {}
weight: 0
