_core:
  default_config_hash: pr8SYyNSNxgY0x14rfFZd6w8mcW8owpW5fO7HNROqC0
favicon_path: ''
favicon_upload: ''
id_centro: '103'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=103&colectivo=TODOS'
nombre_centro: 'Departamento de Filología Inglesa y Alemana'
dir_centro: 'C/ S. Juan Bosco, 7 | 50009 Zaragoza'
telefono_centro: '976 761 538'
mail_centro: sed3004@unizar.es
url_mapa: 'https://www.google.com/maps/place/Calle+de+San+Juan+Bosco,+7,+50009+Zaragoza/@41.644289,-0.903798,17z/data=!3m1!4b1!4m5!3m4!1s0x'
logo_blanco: '7'
facebook: ''
twitter: ''
instagram: ''
meta_desc: 'Departamento de Filología Inglesa y Alemana (Edificio Central de Filosofía y Letras en la Universidad de Zaragoza) en Zaragoza, Huesca y Teruel.'
langcode: es
