_core:
  default_config_hash: indRIdMPzE5ShYHkd7ZXNHthOo0u99zi8mHyKVGCG54
logo_path: 'public://centros_logos_web-15.png'
logo_upload: ''
favicon_path: ''
favicon_upload: ''
id_centro: '127'
nombre_centro: 'Facultad de Ciencias de la Salud'
dir_centro: 'C/ Domingo Miral s/n, 50009 - Zaragoza'
telefono_centro: '+34 976 761 751'
mail_centro: sfcs@unizar.es
url_mapa: /contacto
dir_centro2: ''
telefono_centro2: ''
mail_centro2: ''
url_mapa2: ''
logo_blanco: '1562'
imagen_segundas: '1564'
facebook: ''
twitter: ''
youtube: ''
linkedin: ''
instagram: 'https://www.instagram.com/fcienciassalud_unizar/'
blog: ''
blog_class: ''
soundcloud: ''
meta_desc: 'Grado en Enfermería, Grado en Fisioterapia y Grado en Terapia Ocupacional. Másteres Oficiales. Facultad de Ciencias de la Salud. Universidad de Zaragoza'
langcode: es
