_core:
  default_config_hash: bcjnfiEt6NEY5Fvly0Iow53nlj7MobpFfgS5pmV-onI
langcode: es
smtp_on: true
smtp_host: smtp.unizar.es
smtp_hostbackup: ''
smtp_port: '25'
smtp_protocol: standard
smtp_autotls: true
smtp_timeout: 30
smtp_username: gestweb
smtp_password: 7.Syrox
smtp_from: eps@unizar.es
smtp_fromname: 'Gesti√≥n web'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
smtp_keepalive: false
