blacklist:
- config_split.config_split.magister
- core.entity_view_mode.shortcut.token
- language.types
- migrate_drupal.settings
- shortcut.set.default
- smtp.settings
- unizar_centro.settings
- unizar_base.settings
- unizar_departamento.settings
- system.site
- system.theme
- unizar_admin_menu.settings
- unizar_modulos_configuracion.settings
- block.block.*
- webform.webform.*
- language.entity.*
- asset_injector.css.magister_inyeccion_css
- system.menu.*
- matomo.settings
- language.negotiation
- user.role.administrator
- user.role.anonymous
dependencies: {}
description: ''
folder: ../config/sites/centros/comun/magister
graylist: {}
graylist_dependents: true
graylist_skip_equal: true
id: magister
label: magister
langcode: es
module:
  c11n_migrate: 0
status: true
theme:
  unizar_centro: 0
uuid: 000309f0-7f32-4b5d-8b83-280c91bcc188
weight: 0
