_core:
  default_config_hash: FCvgql2wGbsw-UEDlGKysuLcjRas2EuhAPEgBBFaU64
favicon_path: ''
favicon_upload: ''
id_centro: '83'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=83&colectivo=TODOS'
nombre_centro: 'Departamento de Derecho de la Empresa'
dir_centro: 'C/ Pedro Cerbuna 12  50009 Zaragoza'
telefono_centro: '976761378 - 976761501'
mail_centro: sed4003@unizar.es
url_mapa: 'https://www.google.es/maps/place/41%C2%B038"44.4%22N+0%C2%B053"45.2%22W/@41.645653,-0.895882,930m/data=!3m2!1e3!4b1!4m2!3m1!1s0x'
logo_blanco: '14'
facebook: ''
twitter: ''
meta_desc: 'Universidad de Zaragoza. Departamento de Derecho de la Empresa. Área de Derecho Financiero, Área de Derecho Mercantil, Área de Derecho del Trabajo.'
langcode: es
