_core:
  default_config_hash: XEC8y5M1_Yn2-bik069OjZQjE3IWvYHq6TsD8vwCPmI
favicon_path: ''
favicon_upload: ''
id: '17'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=17&colectivo=TODOS'
nombre_centro: 'Departamento de Farmacología, Fisiología y Medicina Legal y Forense'
dir_centro: 'Facultad de Medicina. C/ Domingo Miral, s/n. 50009 - Zaragoza'
telefono_centro: '976 76 16 99 / 876 55 44 02'
mail_centro: depfarfi@unizar.es
url_mapa: 'https://www.google.es/maps/place/41%C2%B038"44.4%22N+0%C2%B053"45.2%22W/@41.645653,-0.895882,930m/data=!3m2!1e3!4b1!4m2!3m1!1s0x'
logo_blanco: '76'
facebook: ''
twitter: ''
instagram: ''
meta_desc: ''
langcode: es
rrs_header: 0
blog: ''
youtube: ''
linkedin: ''
soundcloud: ''
id_centro: '17'
dir_centro2: ''
mail_centro2: ''
telefono_centro2: ''
url_mapa2: ''
