_core:
  default_config_hash: E2D3uzZoe_sJ54mGQKXevKhz9Pgp19j1utZIc1Xvbac
favicon_path: ''
favicon_upload: ''
id_centro: '23'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=23&colectivo=TODOS'
nombre_centro: 'Dirección y Organización de Empresas'
dir_centro: 'Facultad de Economía y Empresa. Gran Vía, 2'
telefono_centro: '976 76 20 97'
mail_centro: sed4012@unizar.es
url_mapa: 'https://www.google.es/maps/place/41%C2%B038"44.4%22N+0%C2%B053"45.2%22W/@41.645653,-0.895882,930m/data=!3m2!1e3!4b1!4m2!3m1!1s0x'
logo_blanco: '7'
facebook: ''
twitter: ''
meta_desc: ''
langcode: es
