rrs_header: 1
blog: ''
instagram: ''
facebook: 'https://www.facebook.com/iqtma.unizar/'
twitter: ''
youtube: ''
linkedin: ''
soundcloud: ''
dir_centro: 'C/ Mar√≠a de Luna, 3. 50018-Zaragoza'
id: '75'
mail_centro: iqtma@unizar.es
url_mapa: ''
telefono_centro: '+34 876 555 038 | +34 976 761 154'
dir_centro2: ''
mail_centro2: ''
telefono_centro2: ''
url_mapa2: ''
langcode: es
