_core:
  default_config_hash: GlnHDdl9YlPRe_sc697b7jf2AekTKfjOJecBBrMff44
favicon_path: ''
favicon_upload: ''
id: '32'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=32&colectivo=TODOS'
nombre_centro: 'Departamento de Ciencias de la Educaci√≥n'
dir_centro: 'C/ Pedro Cerbuna, 12 - 50009 Zaragoza'
telefono_centro: '976 761315'
mail_centro: sed4001@unizar.es
url_mapa: 'https://goo.gl/maps/eYsdztFGUjBfoNVQ8'
logo_blanco: '69'
facebook: ''
twitter: ''
instagram: ''
meta_desc: ''
langcode: es
