blacklist:
- config_split.config_split.uez
- system.site
- system.theme
- asset_injector.css.uez_inyeccion_css
- core.entity_view_mode.shortcut.token
- shortcut.set.default
- unizar_centro.settings
- unizar_base.settings
- unizar_departamento.settings
- smtp.settings
- language.negotiation
- language.types
- matomo.settings
- unizar_modulos_configuracion.settings
- unizar_admin_menu.settings
- migrate_drupal.settings
- webform.webform.*
- user.role.administrator
- user.role.anonymous
- system.menu.*
- language.entity.*
- block.block.*
dependencies: {}
description: ''
folder: ../config/sites/centros/comun/uez
graylist: {}
graylist_dependents: true
graylist_skip_equal: true
id: uez
label: uez
langcode: es
module:
  c11n_migrate: 0
status: true
theme:
  unizar_centro: 0
uuid: 0fe60b73-b72b-4f66-af27-7ea897b7cc5e
weight: 0
