_core:
  default_config_hash: AXVa8ZVW5I5Q9Sxs1ccDndW79xb6J6tt4rEcc_40td0
logo_path: 'public://salud_deporte_huesca.png'
logo_upload: ''
favicon_path: ''
favicon_upload: ''
id_centro: ''
nombre_centro: 'Facultad de Ciencias de la Salud y del Deporte'
dir_centro: 'Pza. Universidad 3, 22002-Huesca (España)'
telefono_centro: '+34 974 239 393'
mail_centro: secrefsd@unizar.es
url_mapa: /contacto
dir_centro2: ''
telefono_centro2: ''
mail_centro2: ''
url_mapa2: ''
logo_blanco: '2341'
imagen_segundas: '2342'
facebook: 'https://www.facebook.com/FCCSD.Unizar/'
twitter: 'https://twitter.com/FCSD_Unizar'
youtube: ''
linkedin: ''
instagram: ''
soundcloud: ''
meta_desc: 'La Facultad de Ciencias de la Salud y del Deporte de la Universidad de Zaragoza se encuentra en el campus de Huesca. En dicha Facultad actualmente se imparte el primer ciclo del Grado de Medicina, el Grado de Ciencias de la Actividad Física y del Deporte (con sede en el Pabellón Río Isuela), el Grado de Odontología, y el Grado de Nutrición Humana y Dietética.'
langcode: es
