_core:
  default_config_hash: ehJLx7Yh7z7aeuEDCURs3SRSvW2ivzYAt4hVPOuaxJM
favicon_path: ''
favicon_upload: ''
id_centro: '57'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=57&colectivo=TODOS'
nombre_centro: 'Departamento de Ingeniería Eléctrica'
dir_centro: 'C/María de Luna, 3, Edif. Torres Quevedo, 50018 - Zaragoza'
telefono_centro: '976 76 21 52'
mail_centro: sed5009@unizar.es
url_mapa: 'https://www.google.es/maps/place/41%C2%B038"44.4%22N+0%C2%B053"45.2%22W/@41.645653,-0.895882,930m/data=!3m2!1e3!4b1!4m2!3m1!1s0x'
logo_blanco: '41'
facebook: ''
twitter: ''
instagram: ''
meta_desc: ' El Departamento de Ingeniería Eléctrica tiene docencia e investigación en los campos de los Sistemas de Potencia, Energías Renovables y Máquinas Eléctricas.'
langcode: es
