_core:
  default_config_hash: 9jNXOMcoVxZn_5hwh31QlyKfMP-jJkXmvkA96seRNmQ
favicon_path: ''
favicon_upload: ''
id_centro: '69'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=69&colectivo=TODOS'
nombre_centro: 'Departamento de Química Inorgánica'
dir_centro: 'C/ Pedro Cerbuna 12, 50009, Zaragoza.'
telefono_centro: '(+34) 976 76 11 88'
mail_centro: sed2010@unizar.es
url_mapa: 'https://www.google.es/maps/place/41%C2%B038"44.4%22N+0%C2%B053"45.2%22W/@41.645653,-0.895882,930m/data=!3m2!1e3!4b1!4m2!3m1!1s0x'
logo_blanco: '7'
facebook: ''
twitter: ''
meta_desc: ''
langcode: es
