_core:
  default_config_hash: d2tWkLDJpbdEPHzzY5Oe_xy6z1WHtnNxwZUSXiflCMU
favicon_path: ''
favicon_upload: ''
id: '101'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=101&colectivo=TODOS'
nombre_centro: 'Departamento de Anatomía e Histología Humanas'
dir_centro: 'Facultad de Medicina. Edificio A. C/Domingo Miral s/n 50009 Zaragoza'
telefono_centro: '976 761 667'
mail_centro: sed1003@unizar.es
url_mapa: 'https://www.google.es/maps/place/41%C2%B038"44.4%22N+0%C2%B053"45.2%22W/@41.645653,-0.895882,930m/data=!3m2!1e3!4b1!4m2!3m1!1s0x'
logo_blanco: '12'
facebook: ''
twitter: ''
instagram: ''
meta_desc: ''
langcode: es
id_centro: '101'
rrs_header: 0
blog: ''
youtube: ''
linkedin: ''
soundcloud: ''
dir_centro2: ''
mail_centro2: ''
telefono_centro2: ''
url_mapa2: ''
