_core:
  default_config_hash: lY4EQxTHpeOm49jJvN2cbN_ghye-MrXKHe1MrSxptIs
favicon_path: ''
favicon_upload: ''
id_centro: '106'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=106&colectivo=TODOS'
nombre_centro: 'Departamento de Psicología y Sociología'
dir_centro: 'Pedro Cerbuna 12, 50009. Zaragoza-España'
telefono_centro: '976 761 995'
mail_centro: sed4009@unizar.es
url_mapa: 'https://www.google.es/maps/place/41%C2%B038"44.4%22N+0%C2%B053"45.2%22W/@41.645653,-0.895882,930m/data=!3m2!1e3!4b1!4m2!3m1!1s0x'
logo_blanco: '7'
facebook: ''
twitter: ''
meta_desc: 'El departamento de Psicología y Sociología de la Universidad de Zaragoza está compuesto por 184 profesores, distribuidos en 13 centros universitarios, localizados en los campus de Zaragoza, Huesca y Teruel.'
langcode: es
