_core:
  default_config_hash: li8Y-o5_yaXKBTnwCOMOQ_uPmsGKdIv7zi4GvT9I8cU
logo_path: 'public://logo-fyl-ods.jpg'
logo_upload: ''
favicon_path: ''
favicon_upload: ''
id_centro: '103'
nombre_centro: 'Facultad de Filosofía y Letras'
dir_centro: 'San Juan Bosco, 7 - 50009 Zaragoza'
telefono_centro: 'Conserjería: +34 976 76 15 05  |  Secretaría +34 976 76 15 07'
mail_centro: secrefil@unizar.es
url_mapa: /contacto
dir_centro2: ''
telefono_centro2: ''
mail_centro2: ''
url_mapa2: ''
logo_blanco: '2432'
imagen_segundas: '2433'
facebook: 'https://es-es.facebook.com/filosofiayletraszaragoza'
twitter: 'https://twitter.com/facultadfilozgz'
youtube: 'https://www.youtube.com/user/UnizarFyL '
linkedin: ''
instagram: 'https://www.instagram.com/fyl_unizar/?hl=es'
blog: ''
blog_class: ''
soundcloud: ''
meta_desc: 'Institución pública dedicada a la investigación y educación superior que oferta enseñanzas oficiales de grado, máster y doctorado'
langcode: es
