_core:
  default_config_hash: 9DgabkLztscclWQDjei_mAOpxP6xdbp_Iu5L5z6Nsbg
langcode: es
sids:
  ldapnip: ldapnip
authenticationMode: mixed
loginUIUsernameTxt: ''
loginUIPasswordTxt: ''
ldapUserHelpLinkUrl: ''
ldapUserHelpLinkText: 'Cambiar la contrase√±a'
emailOption: disable
emailUpdate: update
emailTemplateHandling: if_empty
emailTemplate: '@username@example.com'
emailTemplateUsageResolveConflict: true
emailTemplateUsageNeverUpdate: false
emailTemplateUsagePromptUser: false
emailTemplateUsageRedirectOnLogin: false
emailTemplateUsagePromptRegex: '.*@unizar\.es'
passwordOption: hide
allowOnlyIfTextInDn: {  }
excludeIfTextInDn: {  }
excludeIfNoAuthorizations: false
skipAdministrators: true
