_core:
  default_config_hash: xGaDFlyXTmhzluhiRhEx58v_3Fu-nMhCzEBF8K4eqHU
langcode: es
drupalAcctProvisionServer: '0'
ldapEntryProvisionServer: '0'
drupalAcctProvisionTriggers:
  drupal_on_login: '0'
  drupal_on_update_create: '0'
ldapEntryProvisionTriggers:
  ldap_on_update_create: '0'
  ldap_on_login: '0'
  ldap_on_delete: '0'
  drupal_on_manual_creation: '0'
orphanedDrupalAcctBehavior: ldap_user_orphan_email
orphanedDrupalAcctReportingInbox: ''
orphanedCheckQty: 100
orphanedAccountCheckInterval: weekly
userConflictResolve: resolve
manualAccountConflict: conflict_reject
acctCreation: ldap_behaviour
userUpdateCronQuery: none
userUpdateCronInterval: daily
ldapUserSyncMappings: {  }
