_core:
  default_config_hash: xGaDFlyXTmhzluhiRhEx58v_3Fu-nMhCzEBF8K4eqHU
langcode: es
drupalAcctProvisionServer: ldapnip
ldapEntryProvisionServer: null
drupalAcctProvisionTriggers:
  - drupal_on_login
  - drupal_on_update_create
ldapEntryProvisionTriggers: {  }
orphanedDrupalAcctBehavior: ldap_user_orphan_do_not_check
orphanedDrupalAcctReportingInbox: ''
orphanedCheckQty: 100
orphanedAccountCheckInterval: weekly
userConflictResolve: resolve
manualAccountConflict: conflict_reject
acctCreation: ldap_behaviour
disableAdminPasswordField: false
userUpdateCronQuery: none
userUpdateCronInterval: daily
ldapUserSyncMappings:
  drupal:
    field-name:
      ldap_attr: '[uid]'
      user_attr: '[field.name]'
      convert: false
      user_tokens: ''
      config_module: ldap_user
      prov_module: ldap_user
      prov_events:
        - create_drupal_user
        - sync_to_drupal_user
