_core:
  default_config_hash: J7xStaa2cDengXK9d3e8TLFmt75yunN9L3gAc1olxmk
ui_localtask: true
ui_checkbox: true
langcode: es
create_revision: false
create_log_entry: false
publish_text_value: Publicar
unpublish_text_value: Despublicar
