_core:
  default_config_hash: Car_5uc2iWj24idQCN_D-ACRWd2Nib2Qge9Rynr0Rro
langcode: es
anonymous: An√≥nimo
verify_mail: true
notify:
  cancel_confirm: true
  password_reset: true
  status_activated: true
  status_blocked: false
  status_canceled: false
  register_admin_created: true
  register_no_approval_required: true
  register_pending_approval: true
register: visitors_admin_approval
cancel_method: user_cancel_block
password_reset_timeout: 86400
password_strength: true
