_core:
  default_config_hash: RW5PhKJvB_D_ZkXWkeWIBaPIZ0zSilGRXx-lv5SgRtg
favicon_path: ''
favicon_upload: ''
id_centro: '53'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=53&colectivo=TODOS'
nombre_centro: 'Departamento de Economía Aplicada'
dir_centro: 'Facultad de Economía y Empresa. Gran Vía, 2. 50005-Zaragoza'
telefono_centro: '976 76 1841'
mail_centro: dd4008@unizar.es
url_mapa: ''
logo_blanco: '8'
facebook: ''
twitter: ''
meta_desc: ''
langcode: es
