_core:
  default_config_hash: rK1y1UeEgSER0Uq7v_VvJjxtoOGpcsj7pKvPtEESMvg
logo_path: 'public://web_ciencias_ods-01.png'
logo_upload: ''
favicon_path: ''
favicon_upload: ''
id_centro: '100'
nombre_centro: 'Facultad de Ciencias'
dir_centro: 'C/ Pedro Cerbuna, 12 - 50009 Zaragoza'
telefono_centro: '+34 976 761 294'
mail_centro: seccienz@unizar.es
url_mapa: 'Balbino Orensanz, 55 casa 3 3ºA'
dir_centro2: 'Balbino Orensanz, 55 casa 3 3ºA'
telefono_centro2: '658662482'
mail_centro2: derecho@unizar.es
url_mapa2: ''
logo_blanco: '13177'
imagen_segundas: '13178'
facebook: 'https://www.facebook.com/pages/Facultad-de-Ciencias/597415503728423 '
twitter: 'https://twitter.com/Ciencias_Unizar '
youtube: 'https://www.youtube.com/channel/UC2qmO505TybNfdaAufb3R6g'
linkedin: ''
instagram: 'https://www.instagram.com/ciencias_unizar/'
blog: ''
blog_class: ''
soundcloud: ''
meta_desc: 'La Facultad de Ciencias es un centro de la Universidad de Zaragoza dedicado a la docencia y a la investigación en el que se imparten titulaciones oficiales de grado y máster, doctorado y varios estudios propios.'
langcode: es
rrs_header: 0
id: ''
