_core:
  default_config_hash: indRIdMPzE5ShYHkd7ZXNHthOo0u99zi8mHyKVGCG54
logo_path: 'public://centros_logos_web-15.png'
logo_upload: ''
favicon_path: ''
favicon_upload: ''
id_centro: '127'
nombre_centro: 'Facultad de Ciencias de la Salud'
dir_centro: 'Avda. Martínez de Velasco, 36  22004 Huesca'
telefono_centro: '+34 974 210 288'
mail_centro: admenfeh@unizar.es
url_mapa: /contacto
dir_centro2: ''
telefono_centro2: ''
mail_centro2: ''
url_mapa2: ''
logo_blanco: '1562'
imagen_segundas: '1564'
facebook: ''
twitter: ''
youtube: ''
linkedin: ''
instagram: ''
blog: ''
blog_class: ''
soundcloud: ''
meta_desc: 'Grado en Enfermería, Grado en Fisioterapia y Grado en Terapia Ocupacional. Másteres Oficiales. Facultad de Ciencias de la Salud. Universidad de Zaragoza'
langcode: es
rrs_header: 0
id: ''
