_core:
  default_config_hash: p53fPqD7CEGZanDMgT4XuI3N6xJBdcz6ewek1T66goU
favicon_path: ''
favicon_upload: ''
id_centro: '122'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=122&colectivo=TODOS'
nombre_centro: 'Departamento de Matem치tica Aplicada'
dir_centro: 'Edificio de Matem치ticas. Pedro Cerbuna 12, 50009 Zaragoza'
telefono_centro: '976 76 11 24 | 976 76 18 85'
mail_centro: dd2005@unizar.es
url_mapa: 'https://www.google.es/maps/place/41%C2%B038"44.4%22N+0%C2%B053"45.2%22W/@41.645653,-0.895882,930m/data=!3m2!1e3!4b1!4m2!3m1!1s0x'
logo_blanco: '11'
facebook: ''
twitter: ''
meta_desc: 'P치gina web Departamento de Matem치tica Aplicada de la Universidad de Zaragoza'
langcode: es
