_core:
  default_config_hash: ITLi6YpGXhKFrZHEDS9PPn221KiIc2lfFI8Lgbx105U
'5:{s:12:''default_logo''': '1'
logo_path: ''
default_favicon: '1'
favicon_path: ''
favicon_mimetype: image/vnd.microsoft.icon
langcode: es
