_core:
  default_config_hash: DxlVgRgV9lXMAkbI6xQqpf_Qbe4useWC1itoqrvimWs
favicon_path: ''
favicon_upload: ''
id_centro: '226'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=226&colectivo=TODOS'
nombre_centro: 'Departamento de Historia'
dir_centro: 'Direcci√≥n del centro'
telefono_centro: '976 76 21 38'
mail_centro: sed3008@unizar.es
url_mapa: 'https://www.google.es/maps/place/41%C2%B038"44.4%22N+0%C2%B053"45.2%22W/@41.645653,-0.895882,930m/data=!3m2!1e3!4b1!4m2!3m1!1s0x'
logo_blanco: '274'
facebook: 'https://www.facebook.com/aragonedadmedia/'
twitter: ''
instagram: ''
meta_desc: ''
langcode: es
