_core:
  default_config_hash: OkX6pcOCdqfhymzqAOzWYLOGd7npCxb5SqM9g4pm4tA
favicon_path: ''
favicon_upload: ''
id_centro: '91'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=91&colectivo=TODOS'
nombre_centro: 'Departamento de Derecho Penal, Filosof√≠a del Derecho e Historia del Derecho'
dir_centro: 'Campus de San Francisco, Pedro Cerbuna 12'
telefono_centro: '976 76 2117'
mail_centro: sed4010@unizar.es
url_mapa: 'https://www.google.es/maps/place/41%C2%B038"44.4%22N+0%C2%B053"45.2%22W/@41.645653,-0.895882,930m/data=!3m2!1e3!4b1!4m2!3m1!1s0x'
logo_blanco: '16'
facebook: ''
twitter: ''
meta_desc: 'El Departamento de Derecho Penal, Filosofia del Derecho e Historia del Derecho de la Universidad de Zaragoza se ubica en la primera planta de la Facultad de Derecho'
langcode: es
