_core:
  default_config_hash: Zdl6iRF0ln7bktIijbSbxDJJhunmyot_QKpC_jcn38g
langcode: es
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: 'public:///logo-svg/cctierra.svg'
  use_default: false
logo_footer_path: ''
logo_footer_upload: {  }
