_core:
  default_config_hash: c4w_CkMlejlY03Vx9EpWnW4KticZITZtPSw90E5tRkk
favicon_path: ''
favicon_upload: ''
id: '108'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=108&colectivo=TODOS'
nombre_centro: 'Departamento de Lingüística y Literaturas Hispánicas'
dir_centro: 'c/ Pedro Cerbuna, 12'
telefono_centro: '976 76 21 36 - 976 76 21 37'
mail_centro: sed3013@unizar.es
url_mapa: 'https://www.google.es/maps/place/41%C2%B038"44.4%22N+0%C2%B053"45.2%22W/@41.645653,-0.895882,930m/data=!3m2!1e3!4b1!4m2!3m1!1s0x'
logo_blanco: '67'
facebook: ''
twitter: ''
instagram: ''
meta_desc: ''
langcode: es
