_core:
  default_config_hash: n29oTVJGpeMhzQFVXj6oLcbIG0hkVQNbO5xl4FPnxZU
logo_path: 'public://facultad_ciencias_sociales_trabajo-01_0.png'
logo_upload: ''
favicon_path: ''
favicon_upload: ''
id_centro: '108'
nombre_centro: 'Facultad de Ciencias Sociales y del Trabajo'
dir_centro: 'Violante de Hungría, 23 - 50009 ZARAGOZA  '
telefono_centro: '+34 976 76 21 21'
mail_centro: sociales@unizar.es
url_mapa: /contacto
dir_centro2: ''
telefono_centro2: ''
mail_centro2: ''
url_mapa2: ''
logo_blanco: '3245'
imagen_segundas: '3246'
facebook: 'https://www.facebook.com/movilidad.fcstunizar.5'
twitter: 'http://www.twitter.com/movsociz'
youtube: ''
linkedin: ''
instagram: ''
soundcloud: ''
meta_desc: 'Facultad de Ciencias Sociales y del Trabajo, Universidad de Zaragoza. Grados (Trabajo Social; Relaciones Laborales y Recursos Humanos), Máster y Doctorado (Relaciones de Género); estudios propios. '
langcode: es
