_core:
  default_config_hash: sbAF4DCWVSelKmM3yxfpH6Acf73OSDzPciXW8EQiUt4
favicon_path: ''
favicon_upload: ''
id_centro: '64'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=64&colectivo=TODOS'
nombre_centro: 'Departamento de Fisiatría y Enfermería'
dir_centro: 'C/Domingo Miral, s/n  50009 Zaragoza'
telefono_centro: '976 76 17 19'
mail_centro: sed1006@unizar.es
url_mapa: 'https://www.google.es/maps/place/41%C2%B038"44.4%22N+0%C2%B053"45.2%22W/@41.645653,-0.895882,930m/data=!3m2!1e3!4b1!4m2!3m1!1s0x'
logo_blanco: '24'
facebook: ''
twitter: ''
meta_desc: ''
langcode: es
