_core:
  default_config_hash: S42gOofZuHsoebaiq6uDfg6cc92bzTcoEBcQfurDsZc
favicon_path: ''
favicon_upload: ''
id_centro: '33'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=33&colectivo=TODOS'
nombre_centro: 'Departamento de Derecho Público'
dir_centro: 'C/ Pedro Cerbuna, 12 - 50009 Zaragoza'
telefono_centro: '+(34)976 76 14 33 | +(34)876 55 36 30'
mail_centro: sed4005@unizar.es
url_mapa: 'https://www.google.es/maps/place/41%C2%B038"44.4%22N+0%C2%B053"45.2%22W/@41.645653,-0.895882,930m/data=!3m2!1e3!4b1!4m2!3m1!1s0x'
logo_blanco: '8'
facebook: ''
twitter: ''
meta_desc: 'Dpto. Derecho Público-Facultad Derecho-Univ. Zaragoza C/Pedro Cerbuna,12 Tl.+(34)976761433 Derecho Administrativo,Constitucional,Internacional Público y Eclesiástico'
langcode: es
