_core:
  default_config_hash: tjuEJPYOSLShFiOhibk657FQXtQq5kymY5RbIu4Kk18
favicon_path: ''
favicon_upload: ''
id: '2'
url_personal: 'https://directorio.unizar.es/rest/persona/unidad_persona_web?cod_unidad=2&colectivo=TODOS'
nombre_centro: 'Departamento de Anatomía, Embriología y Genética Animal'
dir_centro: 'Facultad de Veterinaria  C/ Miguel Servet 177   50013 ZARAGOZA.-'
telefono_centro: '976 76 16 04'
mail_centro: ndaeg@unizar.es
url_mapa: 'https://www.google.es/maps/place/41%C2%B038"44.4%22N+0%C2%B053"45.2%22W/@41.645653,-0.895882,930m/data=!3m2!1e3!4b1!4m2!3m1!1s0x'
logo_blanco: '7'
facebook: ''
twitter: ''
meta_desc: 'Departamento de Anatomía, Embriología y Genética Animal de la Facultad de Veterinaria de la Universidad de Zaragoza. '
langcode: es
